export const arrayM = [
  {
    id: 1,
    image: 'peitoral-m',
    label: 'Peitoral',
    value: 'Peitoral',
    titulo: 'Treino para fortalecimento do peitoral',
  },
  {
    id: 2,
    image: 'ombros-m',
    label: 'Ombros',
    value: 'Ombros',
    titulo: 'Treino para divisão da musculatura do ombros',
  },
  {
    id: 7,
    image: 'dorsal-m',
    label: 'Dorsal',
    value: 'Dorsal',
    titulo: 'Treino para costas e trapézio',
  },
  { id: 3, image: 'braco-m', label: 'Braço', value: 'Braço', titulo: 'Treino de Biceps e triceps' },
  {
    id: 4,
    image: 'pernas-m',
    label: 'Pernas',
    value: 'Pernas',
    titulo: 'Treino para fortalecer o quadríceps, posterior e paturilha.',
  },
  {
    id: 5,
    image: 'gluteos-m',
    label: 'Glúteos',
    value: 'Glúteos',
    titulo: 'Trabalhar a musculatura do bumbum',
  },
  { id: 6, image: 'cardio-m', label: 'Cardío', value: 'Cardío', titulo: 'Exercicios misto para' },
  {
    id: 8,
    image: 'abdomen-m',
    label: 'Abdominais',
    value: 'Abdominais',
    titulo: 'Treino de fortalecimento adbominal',
  },
];

export const arrayF = [
  {
    id: 1,
    image: 'peitoral-f',
    label: 'Peitoral',
    value: 'Peitoral',
    titulo: 'Treino para fortalecimento do peitoral',
  },
  {
    id: 2,
    image: 'ombros-f',
    label: 'Ombros',
    value: 'Ombros',
    titulo: 'Treino para divisão da musculatura dos ombros',
  },
  {
    id: 7,
    image: 'dorsal-f',
    label: 'Dorsal',
    value: 'Dorsal',
    titulo: 'Treino para costas e trapézio',
  },
  {
    id: 3,
    image: 'braco-f',
    label: 'Braço',
    value: 'Braço',
    titulo: 'Treino de Biceps e triceps',
  },
  {
    id: 4,
    image: 'pernas-f',
    label: 'Pernas',
    value: 'Pernas',
    titulo: 'Treino para fortalecer o quadríceps, posterior e paturilha.',
  },
  {
    id: 5,
    image: 'gluteos-f',
    label: 'Glúteos',
    value: 'Glúteos',
    titulo: 'Trabalhar a musculatura do bumbum',
  },
  { id: 6, image: 'cardio-f', label: 'Cardío', value: 'Peitoral', titulo: 'Exercicios misto para' },
  {
    id: 8,
    image: 'abdomen-f',
    label: 'Abdominais',
    value: 'Abdominais',
    titulo: 'Treino de fortalecimento adbominal',
  },
];
