import uuid from 'react-native-uuid';

export const EvolucaoSchema = {
  name: 'Evolucao',
  properties: {
    _id: 'string',
    treino: 'string',
    grupoMuscular: 'string',
    dataTreino: 'string',
    pesoLevantado: 'int',
    totalSets: 'int',
    totalSeries: 'int',
    tempoTreino: 'int',
    calorias: 'float',
    peso: 'float',
    bracoDireito: 'float',
    bracoEsquerdo: 'float',
    antebracoDireito: 'float',
    antebracoEsquerdo: 'float',
    pernaDireita: 'float',
    pernaEsquerda: 'float',
    cintura: 'float',
    quadril: 'float',
    peitoral: 'float',
    gorduraCorporal: 'float',
  },
  primaryKey: '_id',
};

export const EvolucaoInitial = {
  // _id: uuid.v4(),
  treino: '',
  grupoMuscular: '',
  dataTreino: '',
  pesoLevantado: 0,
  totalSets: 0,
  totalSeries: 0,
  tempoTreino: 0,
  calorias: 0,
  peso: 0,
  bracoDireito: 0,
  bracoEsquerdo: 0,
  antebracoDireito: 0,
  antebracoEsquerdo: 0,
  pernaDireita: 0,
  pernaEsquerda: 0,
  cintura: 0,
  quadril: 0,
  peitoral: 0,
  gorduraCorporal: 0,
};
