import uuid from 'react-native-uuid';

export const UsuarioSchema = {
  name: 'Usuario',
  properties: {
    _id: 'string',
    nome: 'string',
    dataNascimento: 'date',
    genero: 'string',
    image:'string',
    diasTreinos: 'string',
    objetivo: 'string',
    tipoPlano: 'string',
    experiencia: 'string',
    altura:'float',
    peso: 'float',
    bracoDireito: 'float',
    bracoEsquerdo: 'float',
    antebracoDireito: 'float',
    antebracoEsquerdo: 'float',
    pernaDireita: 'float',
    pernaEsquerda: 'float',
    panturilhaDireita: 'float',
    panturilhaEsquerda: 'float',
    cintura: 'float',
    quadril: 'float',
    peito: 'float',
    gorduraCorporal: 'float',
    treinoAtual: 'string',
  },
  primaryKey: '_id',
};

export const UsuarioInitial = {
  // _id: uuid.v4(),
  nome: '',
  dataNascimento: new Date(),
  genero: 'M',
  image:'',
  diasTreinos: '',
  objetivo: '',
  tipoPlano: 'premium',
  experiencia: '',
  altura: 0,
  peso: 0,
  bracoDireito: 0,
  bracoEsquerdo: 0,
  antebracoDireito: 0,
  antebracoEsquerdo: 0,
  pernaDireita: 0,
  pernaEsquerda: 0,
  panturilhaDireita:0,
  panturilhaEsquerda:0,
  cintura: 0,
  quadril: 0,
  peito: 0,
  gorduraCorporal: 0,
  treinoAtual: 'A',
};
